package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    params {
        add {
            password("env.DATABASE_PASSWORD", "credentialsJSON:f42d51ff-072d-40f6-90fa-ff61c452cc56", display = ParameterDisplay.HIDDEN)
        }
    }

    expectSteps {
        exec {
            path = "build.sh"
            arguments = "Up --skip"
        }
    }
    steps {
        insert(0) {
            step {
                name = "Production docker-compose configuration"
                type = "djangolibrary_CreateTextFile"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/docker-compose.override.yml")
                param("content", """
                    version: "3.8"
                    
                    services:
                      web:
                        build:
                          args:
                            PASS: %env.DATABASE_PASSWORD%
                """.trimIndent())
            }
        }
        update<ExecBuildStep>(1) {
            clearConditions()
        }
    }
}
