version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migrations
  
  superuser:
    build: .
    command: python manage.py createsuperuser --noinput
  
  migrations:
    build: .
    command: python manage.py migrate --noinput
    depends_on:
      - superuser